# Generated by Django 2.1.5 on 2020-02-04 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Pessoas',
        ),
    ]
