# Generated by Django 2.1.5 on 2020-02-18 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200204_1258'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pessoas',
        ),
    ]
